### ISSUE TITLE
Strikers

### ISSUE THREAD

**Issue by AIPE900** [ultimate-guides/ultimate-guide-98-data#6]
Al rato de abrir los strikers no sale la descripcion de los efectos, solo salen letras  al azar #

**Comment by ultimate-guides** [comment]
Ya esta siendo atendido, si gustas tener acceso anticipado puedes unirte a las versiones BETA
https://play.google.com/apps/testing/com.ultimateguides.ultimatePro

Ahi estamos arreglando varias cosas que aun no salen A la version final de la playstore. 

Nota: De ahora en adelante se va a notificar al usuario si alguna descripcion no se encuentra disponible, ya que las traducciones de los strikers nunca las hemos manejado, esperemos que la gente aporte y empiece a traducir esa parte, sino eventualmente nosotros lo haremos saludos. gracias por reportar

**Comment by AIPE900** [comment]
Buenas noches

Queria informarles que me parece una excelente app que ayuda a los jugadores, ya soy beta teaster y bueno algo mas que me llama la atencion es que el menu principal por ejemplo no se encuentra traducido

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by ultimate-guides** [comment]
La version 1.0.6 Ya esta disponible, aunque no esta 100% arreglada la parte de los strikers, por lo menos ahora va a notificar al usuario que esa traduccion no existe, y cuando alguien modifque los archivos o agrege traducciones ya se veran reflejadas en la APP. Ya no mostrara contenido al Azar como mencionabas saludos!
