### ISSUE TITLE
Pending update of new events

### ISSUE THREAD

**Issue by Sangogrin** [ultimate-guides/ultimate-guide-98-data#9]
Superpower Drill 

Dates: July 24, 5:00 am ~ July 25, 5:00 am

Requirements: Level 15+

Details: Train your superpower by charging the crystal ball and get rewards! 

.

Gold Rush Chance+2

Dates: July 24, 5:00 am ~ July 25, 5:00 am

Requirements: Level 18+

Details: Gold Rush challenge chance+2 during the event! Come challenge Gold Rush stages! 

.

1 of 2 Lucky Draw

Dates: July 24, 5:00 am ~ July 27, 5:00 am

Requirements: Account registered for 22 days. Server open for 14 days. Level 20+

Details: 1 of 2 Lucky Draw is coming! Shion and Catty Leona are waiting for you! Don't miss out!

.

Weapons Egg Machine

Dates: July 24, 5:00 am ~ July 27, 5:00 am

Requirements: Server open for 21 days

Details: During the event, use Egg Machine, and there is chance to get Shion awaken weapon frag, tome, badge and other rare items.

.

Weapons Egg Machine

Dates: July 24, 5:00 am ~ July 27, 5:00 am

Requirements: Server open for 21 days

Details: During the event, use Egg Machine, and there is chance to get Catty Leona awaken weapon frag, tome, badge and other rare items.

.

Lucky Draw Rewards

Dates: July 24, 5:00 am ~ July 27, 5:00 am

Requirements: Account registered for 22 days

Details: Draw a certain number of times in Lucky Draw during the event to get rich rare items!

.

Spend for Rewards

Dates: July 24, 5:00 am ~ July 27, 5:00 am

Requirements: Account registered for 11 days

Details: Spend a certain amount of diamonds during the event and get awesome rewards!

.

Top-up for reward

Dates: July 24, 5:00 am ~ July 31, 5:00 am

Requirements: Server open for 21 days

Details: Top-up 225 Diamonds every day during the event for rewards, top-up 5 out of 7 days to claim the mega reward!

.

Super Scratcher

Dates: July 25, 5:00 am ~ July 26, 5:00 am

Requirements: Level 20+

Details: Super Gold Scratcher is here, who knows what you may get!

.

Team Battle to get May Lee

Dates: July 25, 12:00 noon ~ July 26, 12:00 noon

Requirements: Account registered for 8 days. Level 40+

Details: Defeat the May Lee clones a certain number of times during the event to get May Lee[Frag].

.

Task Rewards

Dates: July 25, 5:00 am ~ July 27, 5:00 am

Requirements: Account registered for 8 days. Level 25+

Details: Complete certain tasks and claim awesome rewards! (Daily Reset)

.

Fashion Pack

Dates: July 25, 5:00 am ~ July 27, 5:00 am

Requirements: Server open for 22 days. Level 9

Details: Rare fashion for Shion is available during the event. 

.

Shermie Adventure

Dates: July 26, 5:00 am ~ July 27, 5:00 am

Requirements: Level 24+

Details: Welcome to Shermie Adventure. Embark on a fun filled adventure with Shermie and find amazing treasures.

.

Team Battle to get Athena 2002 UM

Dates: July 26, 12:00 noon ~ July 27, 12:00 noon

Requirements: Account registered for 8 days. Level 40+

Details: Defeat the Athena 2002 UM clones a certain number of times during the event to get Athena 2002 UM[Frag].

.

Time-limited Gift Pack

Dates: July 26, 5:00 am ~ July 27, 5:00 am

Requirements: Account registered for 20 days

.

Minigame - Seal Orochi

Dates: July 27, 5:00 am ~ July 28, 5:00 am

Requirements: Account registered for 8 days. Level 15+

Details: Mini game - Seal Orochi unlocked! Come help seal Orochi Now!

.

Female Fighters Challenge Chance+2

Dates: July 27, 5:00 am ~ July 28, 5:00 am

Requirements: Level 18+

Details: Female Fighters Challenge chance+2 during the event! Come challenge Female Fighters Challenge stages! 

.

Rewards for Trial Points

Dates: July 27, 5:00 am ~ July 29, 5:00 am

Requirements: Account registered for 8 days. Level 25+

Details: Accumulate certain quantity of ultimate trial points during the event and claim extra rewards! (Daily Reset)

.

Orange Esoteric Exchange

Dates: July 27, 5:00 am ~ July 29, 5:00 am

Requirements: Level 80+

Details: During the event, you can exchange Orange Esoteric Stone[frag] for Orange Esoteric Stone and ULT Esoteric Stone! 

.

Orange Esoteric Exchange

Dates: July 27, 5:00 am ~ July 29, 5:00 am

Requirements: Level 80+

Details: During the event, you can exchange certain Orange Esoteric Stone for Orange Esoteric Stone[frag]! 

.

Draw Esoteric Stone for rewards

Dates: July 27, 5:00 am ~ July 29, 5:00 am

Requirements: Level 66+

Details: During the event, open Esoteric Chest for certain times to gain extra rewards!

.

ULT Esoteric Stone Limited Exchange

Dates: July 27, 5:00 am ~ July 29, 5:00 am

Requirements: Level 66+

Details: Exchange for ULT Esoteric Stones during the event, don't miss out! (Daily Reset)

.

Shake&Shake

Dates: July 27, 5:00 am ~ July 31, 5:00 am

Requirements: Account registered for 20 days

Details: Come to Shake&Shake, a lot of amazing rewards are waiting for you! (Daily Reset)

.

Work Benefits

Dates: July 27, 5:00 am ~ Aug 1, 5:00 am

Requirements: Account registered for 4 days. Level 25+

Details: A new week begins, and it's time to start work again! Complete tasks and get great rewards!

.

Kula's Fruits Adventure

Dates: July 28, 5:00 am ~ July 29, 5:00 am

Requirements: Level 15+

Details: Come and eat fruits with Kula to get rewards! 

.

Mirage Challenge Chance+2

Dates: July 28, 5:00 am ~ July 29, 5:00 am

Requirements: Level 18+

Details: Mirage Challenge chance+2 during the event! Come challenge Mirage Challenge stages!

.

Pop Balloons

Dates: July 29, 5:00 am ~ July 30, 5:00 am

Requirements: Level 23+

Details: Pop Balloons is unlocked during the event. Hit the balloon accurately to get rich rewards!

.

Team Battle to get Ukyo Tachibana

Dates: July 29, 12:00 noon ~ July 30, 12:00 noon

Requirements: Account registered for 8 days. Level 40+

Details: Defeat the Ukyo Tachibana clones a certain number of times during the event to get Ukyo Tachibana[Frag].

.

Double Gold in Trial Hidden Safe

Dates: July 29, 5:00 am ~ July 31, 5:00 am

Requirements: Level 25+

Details: Opening hidden safes in Ultimate Trials for double Golds, come get it now! (Only doubled for free tries) (Daily Reset)

.

Gene Map Draw Gift

Dates: July 29, 5:00 am ~ July 31, 5:00 am

Requirements: Server open for 150 days. Level 85+

.

ULT Esoteric Exchange

Dates: July 29, 5:00 am ~ July 31, 5:00 am

Requirements: Level 90+

Details: During the event, you can use Red Esoteric Orig Stone to exchange Ult Esoteric Stone! 

.

ULT Esoteric Exchange

Dates: July 29, 5:00 am ~ July 31, 5:00 am

Requirements: Level 90+

During the event, you can use certain Ult Esoteric Stone to exchange Red Esoteric Orig Stone! 

.

Mini game-Aircraft

Dates: July 30, 5:00 am ~ July 31, 5:00 am

Requirements: Level 30+

Details: Aircraft Game is here, take your fight into the skies, let's go!

.

Team Battle to get Maki Kagura

Dates: July 30, 12:00 noon ~ July 31, 12:00 noon

Requirements: Account registered for 8 days. Level 40+

Details: Defeat the Maki Kagura clones a certain number of times during the event to get Maki Kagura[Frag].

.

Kyo's Tower Drop

Dates: July 31, 5:00 am ~ Aug 1, 5:00 am

Requirements: Level 23+

Details: Kyo's Tower Drop is available during the event. Get rich rewards with your wit!

.

EXP Rush Challenge Chance+2

Dates: July 31, 5:00 am ~ Aug 1, 5:00 am

Requirements: Level 18+

Details: EXP Rush Challenge chance+2 during the event! Come challenge EXP Rush Challenge stages! 

.

Campaign Rewards Doubled

Dates: July 31, 5:00 am ~ Aug 2, 5:00 am

Requirements: Account registered for 3 days. Level 15+

Details: During the event, you can get double earnings in Main Campaigns. (Daily Reset)

.

SP on Sale

Dates: July 31, 5:00 am ~ Aug 2, 5:00 am

Requirements: Account registered for 8 days. Level 25+

Details: Purchase SP a certain number of times during the event to gain extra rewards! (Daily Reset)

.

Fighter Fragment Exchange

Dates: July 31, 5:00 am ~ Aug 2, 5:00 am

Requirements: Account registered for 8 days

Details: Exchange for the fighter fragments you need now, don't miss this rare opportunity!

.

Fighter Fashion Sale

Dates: July 31, 5:00 am ~ Aug 2, 5:00 am

Requirements: Account registered for 15 days. Level 25+

Details: Time-limited Fighter Fashion on sale! Come get some new clothes for your fighters!

.

Open Equipment Chests for Rewards

Dates: July 31, 5:00 am ~ Aug 2, 5:00 am

Requirements: Account registered for 11 days. Level 10+

Details: Open Equipment Chest during the event to get various items!

.

Equipment Frag Exchange

Dates: July 31, 5:00 am ~ Aug 2, 5:00 am

Requirements: Account registered for 8 days. Level 25+

Details: Weapons can be exchanged for "Equipment Frag" during the event, and you can exchange "Equipment Frag" for useful weapons. 

.

First x10 Equipment Chest 50% off

Dates: July 31, 5:00 am ~ Aug 2, 5:00 am

Requirements: Level 24+

Details: During the event, 50% off for first Openx10 of Equipment Chest every day! (Daily Reset)

.

Ash Secret Garden

Dates: Aug 1, 5:00 am ~ Aug 2, 5:00 am

Requirements: Level 24+

Details: What treasures can you dig up from Ash secret garden? Come check it out!

.

Gold Rush Chance+2

Dates: Aug 1, 5:00 am ~ Aug 2, 5:00 am

Requirements: Level 18+

Details: Gold Rush challenge chance+2 during the event! Come challenge Gold Rush stages! 

.

2048 Challenge

Dates: Aug 2, 5:00 am ~ Aug 3, 5:00 am

Requirements: Level 5+

Details: What are you waiting for, come challenge it now, be the first to get 2048!

.

Team Battle to get Omega Rugal

Dates: Aug 2, 12:00 noon ~ Aug 3, 12:00 noon

Requirements: Account registered for 8 days. Level 40+

Details: Defeat the Omega Rugal clones a certain number of times during the event to get Omega Rugal[Frag].

.

Campaign Master

Dates: Aug 2, 5:00 am ~ Aug 4, 5:00 am

Details: Challenge the Main Campaign to get extra rewards. (Daily Reset)

.

Badge Exchange

Dates: Aug 2, 5:00 am ~ Aug 3, 5:00 am

Requirements: Account registered for 6 days. Level 25+

Details: Badge and Badge material can be exchanged for one another during the event, please take note that each badge can only be exchanged once, choose carefully!

.

Fighter Equipment Pack (Death Vice)

Dates: Aug 2, 5:00 am ~ Aug 5, 5:00 am

Requirements: Server open for 21 days

Details: Equipment pack can increase Death Vice to:

Equipment quality: Purple+4

Skill level: 68

.

Fighter Upgrade Pack (Death Vice)

Dates: Aug 2, 5:00 am ~ Aug 5, 5:00 am

Requirements: Server open for 21 days

Details: Upgrade pack can increase Death Vice to:

Fighter level: 68

Fighter quality: Orange

.

Time-limited Chest (Death Vice)

Dates: Aug 2, 5:00 am ~ Aug 7, 5:00 am

Requirements: Server open for 14 days. Level 20+

.

Slot Machine

Dates: Aug 2, 5:00 am ~ Aug 7, 5:00 am

Requirements: Server open for 14 days. Level 20+

.

Cumulative Recharge for Resource

Dates: Aug 2, 5:00 am ~ Aug 7, 5:00 am

Requirements: Account registered for 11 days. Level 15+

Details: Cumulatively recharge a certain amount for valuable items! 

.

Mini game-Eat Buns

Dates: Aug 3, 5:00 am ~ Aug 4, 5:00 am

Requirements: Level 20+

Details: Kensou eats Buns during the event. Play the game and claim rewards!

.

Team Battle to get Igniz

Dates: Aug 3, 12:00 noon ~ Aug 4, 12:00 noon

Requirements: Account registered for 8 days. Level 40+

Details: Defeat the Igniz clones a certain number of times during the event to get Igniz[Frag].

.

Weekend Bank

Dates: Aug 3, 5:00 am ~ Aug 10, 5:00 am

Requirements: Level 9+

Details: Sign in to get rewards, and get a lot of diamonds at weekends! 

.

Promotion Gem Exchange

Dates: Aug 3, 5:00 am ~ Aug 4, 5:00 am

Requirements: Account registered for 20 days

Details: Promotion Gem exchange during the event, come join it! 

.

Kula Defense War

Dates: Aug 4, 5:00 am ~ Aug 5, 5:00 am

Requirements: Level 23+

Details: Kula Defense War unlocks during the event, test your speed and claim great rewards!

.

Mirage Challenge Chance+2

Dates: Aug 4, 5:00 am ~ Aug 5, 5:00 am

Requirements: Level 18+

Details: Mirage Challenge chance+2 during the event! Come challenge Mirage Challenge stages!

.

Rewards for Arena Points

Dates: Aug 4, 5:00 am ~ Aug 6, 5:00 am

Requirements: Account registered for 8 days. Level 15+

Details: Accumulate certain quantity of arena points during the event and claim extra rewards! (Daily Reset)

.

Time-Limited Exchange

Dates: Aug 4, 5:00 am ~ Aug 5, 5:00 am

Details: Exchange for rare items during the event, don't miss out!

.

Mystic Store

Dates: Aug 4, 5:00 am ~ Aug 5, 5:00 am

Requirements: Account registered for 8 days. Level 25+

Details: BOSS fighter cuisine available in Mystic store during the event.

.

Superpower Drill 

Dates: Aug 5, 5:00 am ~ Aug 6, 5:00 am

Requirements: Level 15+

Details: Train your superpower by charging the crystal ball and get rewards! 

.

Female Fighters Challenge Chance+2

Dates: Aug 5, 5:00 am ~ Aug 6, 5:00 am

Requirements: Level 18+

Details: Female Fighters Challenge chance+2 during the event! Come challenge Female Fighters Challenge stages! 

.

Aid Pack Exchange

Dates: Aug 5, 5:00 am ~ Aug 7, 5:00 am

Requirements: Level 73+

Details: During the event, fighter aid pack unlocks for limited time! Get it now!

.

Fighter Weapon Awakening Frag Pack Exchange

Dates: Aug 5, 5:00 am ~ Aug 7, 5:00 am

Requirements: Level 10+

Details: During the event, fighter weapon frags are available for limited time. Get it now!

.

Super Scratcher

Dates: Aug 6, 5:00 am ~ Aug 7, 5:00 am

Requirements: Level 20+

Details: Super Gold Scratcher is here, who knows what you may get!

.

Team Battle to get Kula

Dates: Aug 6, 12:00 noon ~ Aug 7, 12:00 noon

Requirements: Account registered for 8 days. Level 40+

Details: Defeat the Kula clones a certain number of times during the event to get Kula[Frag].

.

Elite Campaign Chances+3

Dates: Aug 6, 5:00 am ~ Aug 8, 5:00 am

Requirements: Account registered for 3 days. Level 15+

Details: During the event, Elite Campaign chances+3, go challenge and get the fighter fragment you need now! 

.

Tome Exchange

Dates: Aug 6, 5:00 am ~ Aug 7, 5:00 am

Requirements: Account registered for 6 days. Level 25+

Details: Tome and Tome material can be exchanged for one another during the event, please take note that each Tome can only be exchanged once, choose carefully!

.

Aid Skill Book Exchange

Dates: Aug 5, 5:00 am ~ Aug 7, 5:00 am

Requirements: Level 73+

Details: During the event, Fighter Aid Skill Book unlocks for limited time! Get it now!

**Comment by Sangogrin** [comment]
Events period from 23-07-20 to 05-08-20

**Comment by ultimate-guides** [comment]
Ya quedaron gracias por notificar
